const SET_USERS = 'SET_USERS'
const SET_SHOES = 'SET_SHOES'
const SET_CATEGORIES = 'SET_CATEGORIES'
const SEARCH_BY_NAME = 'SEARCH_BY_NAME'

export {
  SET_USERS,
  SET_SHOES,
  SET_CATEGORIES,
  SEARCH_BY_NAME
}