const SET_USERS = 'SET_USERS'
const SET_SHOES = 'SET_SHOES'
const SET_CATEGORIES = 'SET_CATEGORIES'
const CREATE_SHOES = 'CREATE_SHOES'

export{
  SET_USERS,
  SET_SHOES,
  SET_CATEGORIES,
  CREATE_SHOES
}